package EegDataParser.masterdata;

import static EegDataParser.masterdata.Plat.PLAT_CZOLOWY;

import java.util.Arrays;
import java.util.List;

public enum Odprowadzenie {
	O1(PLAT_CZOLOWY, "O39"),
	O2(PLAT_CZOLOWY),
	O3(PLAT_CZOLOWY),
	O4(PLAT_CZOLOWY),
	O5(PLAT_CZOLOWY),
	O6(PLAT_CZOLOWY),
	O7(PLAT_CZOLOWY),
	O8(PLAT_CZOLOWY),
	O9(PLAT_CZOLOWY),
	O10(PLAT_CZOLOWY),
	O11(PLAT_CZOLOWY),
	O12(PLAT_CZOLOWY),
	O13(PLAT_CZOLOWY),
	O14(PLAT_CZOLOWY),
	O15(PLAT_CZOLOWY),
	O16(PLAT_CZOLOWY),
	O17(PLAT_CZOLOWY),
	O18(PLAT_CZOLOWY),
	O19(PLAT_CZOLOWY),
	O20(PLAT_CZOLOWY),
	O21(PLAT_CZOLOWY),
	O22(PLAT_CZOLOWY),
	O23(PLAT_CZOLOWY),
	O24(PLAT_CZOLOWY),
	O25(PLAT_CZOLOWY),
	O26(PLAT_CZOLOWY),
	O27(PLAT_CZOLOWY),
	O28(PLAT_CZOLOWY),
	O29(PLAT_CZOLOWY),
	O30(PLAT_CZOLOWY),
	O31(PLAT_CZOLOWY),
	O32(PLAT_CZOLOWY),
	O33(PLAT_CZOLOWY),
	O34(PLAT_CZOLOWY),
	O35(PLAT_CZOLOWY),
	O36(PLAT_CZOLOWY),
	O37(PLAT_CZOLOWY),
	O38(PLAT_CZOLOWY),
	O39(PLAT_CZOLOWY),
	O40(PLAT_CZOLOWY),
	O41(PLAT_CZOLOWY),
	O42(PLAT_CZOLOWY),
	O43(PLAT_CZOLOWY),
	O44(PLAT_CZOLOWY),
	O45(PLAT_CZOLOWY),
	O46(PLAT_CZOLOWY),
	O47(PLAT_CZOLOWY),
	O48(PLAT_CZOLOWY),
	O49(PLAT_CZOLOWY),
	O50(PLAT_CZOLOWY),
	O51(PLAT_CZOLOWY),
	O52(PLAT_CZOLOWY),
	O53(PLAT_CZOLOWY),
	O54(PLAT_CZOLOWY),
	O55(PLAT_CZOLOWY),
	O56(PLAT_CZOLOWY),
	O57(PLAT_CZOLOWY),
	O58(PLAT_CZOLOWY),
	O59(PLAT_CZOLOWY),
	O60(PLAT_CZOLOWY),
	O61(PLAT_CZOLOWY),
	O62(PLAT_CZOLOWY),
	O63(PLAT_CZOLOWY);
	
	private List<String> sasiednieOdprowadzenia;
	private Plat plat;
	
	Odprowadzenie(Plat plat, String...odprowadzenia) {
		this.plat = plat;
		sasiednieOdprowadzenia = Arrays.asList(odprowadzenia);
	}
	
	public List<String> getNeighbors() {
		return sasiednieOdprowadzenia;
	}
}
